version: '3.8'
services:
  superlink:
    image: flwr/superlink:1.15.2
    container_name: superlink
    command:
    - --insecure
    - --isolation
    - process
    ports:
    - 9091:9091
    - 9092:9092
    - 9093:9093
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  serverapp:
    build:
      context: .
      dockerfile: serverapp.Dockerfile
    image: flwr_serverapp:0.0.1
    container_name: serverapp
    command:
    - --insecure
    - --serverappio-api-address
    - superlink:9091
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
    environment:
      LOG_DIR: /app/logs
  supernode-1:
    image: flwr/supernode:1.15.2
    container_name: supernode-1
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=0 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9094
    - --isolation
    - process
    ports:
    - 9094:9094
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-1:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-1
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-1:9094
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '1.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '1'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '0'
      PROFILE_NAME: Low-End IoT
    volumes:
    - logs:/app/logs:rw
  supernode-2:
    image: flwr/supernode:1.15.2
    container_name: supernode-2
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=1 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9095
    - --isolation
    - process
    ports:
    - 9095:9095
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-2:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-2
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-2:9095
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '3.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '3'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '1'
      PROFILE_NAME: Mid-Range Edge
    volumes:
    - logs:/app/logs:rw
  supernode-3:
    image: flwr/supernode:1.15.2
    container_name: supernode-3
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=2 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9096
    - --isolation
    - process
    ports:
    - 9096:9096
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-3:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-3
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-3:9096
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '6.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '6'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '2'
      PROFILE_NAME: High-End Edge CPU
    volumes:
    - logs:/app/logs:rw
  supernode-4:
    image: flwr/supernode:1.15.2
    container_name: supernode-4
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=3 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9097
    - --isolation
    - process
    ports:
    - 9097:9097
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-4:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-4
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-4:9097
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '2.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '2'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '3'
      PROFILE_NAME: Low-End IoT
    volumes:
    - logs:/app/logs:rw
  supernode-5:
    image: flwr/supernode:1.15.2
    container_name: supernode-5
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=4 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9098
    - --isolation
    - process
    ports:
    - 9098:9098
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-5:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-5
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-5:9098
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '3.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '3'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '4'
      PROFILE_NAME: Mid-Range Edge
    volumes:
    - logs:/app/logs:rw
  supernode-6:
    image: flwr/supernode:1.15.2
    container_name: supernode-6
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=5 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9099
    - --isolation
    - process
    ports:
    - 9099:9099
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-6:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-6
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-6:9099
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '4.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '4'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '5'
      PROFILE_NAME: High-End Edge CPU
    volumes:
    - logs:/app/logs:rw
  supernode-7:
    image: flwr/supernode:1.15.2
    container_name: supernode-7
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=6 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9100
    - --isolation
    - process
    ports:
    - 9100:9100
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-7:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-7
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-7:9100
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '2.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '2'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '6'
      PROFILE_NAME: Low-End IoT
    volumes:
    - logs:/app/logs:rw
  supernode-8:
    image: flwr/supernode:1.15.2
    container_name: supernode-8
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=7 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9101
    - --isolation
    - process
    ports:
    - 9101:9101
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-8:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-8
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-8:9101
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '4.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '4'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '7'
      PROFILE_NAME: Mid-Range Edge
    volumes:
    - logs:/app/logs:rw
  supernode-9:
    image: flwr/supernode:1.15.2
    container_name: supernode-9
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=8 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9102
    - --isolation
    - process
    ports:
    - 9102:9102
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-9:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-9
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-9:9102
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '6.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '6'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '8'
      PROFILE_NAME: High-End Edge CPU
    volumes:
    - logs:/app/logs:rw
  supernode-10:
    image: flwr/supernode:1.15.2
    container_name: supernode-10
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=9 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9103
    - --isolation
    - process
    ports:
    - 9103:9103
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-10:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-10
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-10:9103
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '2.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '2'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '9'
      PROFILE_NAME: Low-End IoT
    volumes:
    - logs:/app/logs:rw
  supernode-11:
    image: flwr/supernode:1.15.2
    container_name: supernode-11
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=10 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9104
    - --isolation
    - process
    ports:
    - 9104:9104
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-11:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-11
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-11:9104
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '2.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '2'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '10'
      PROFILE_NAME: Mid-Range Edge
    volumes:
    - logs:/app/logs:rw
  supernode-12:
    image: flwr/supernode:1.15.2
    container_name: supernode-12
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=11 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9105
    - --isolation
    - process
    ports:
    - 9105:9105
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-12:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-12
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-12:9105
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '8.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '8'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '11'
      PROFILE_NAME: High-End Edge CPU
    volumes:
    - logs:/app/logs:rw
  supernode-13:
    image: flwr/supernode:1.15.2
    container_name: supernode-13
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=12 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9106
    - --isolation
    - process
    ports:
    - 9106:9106
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-13:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-13
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-13:9106
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '1.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '1'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '12'
      PROFILE_NAME: Low-End IoT
    volumes:
    - logs:/app/logs:rw
  supernode-14:
    image: flwr/supernode:1.15.2
    container_name: supernode-14
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=13 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9107
    - --isolation
    - process
    ports:
    - 9107:9107
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-14:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-14
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-14:9107
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '4.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '4'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '13'
      PROFILE_NAME: Mid-Range Edge
    volumes:
    - logs:/app/logs:rw
  supernode-15:
    image: flwr/supernode:1.15.2
    container_name: supernode-15
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=14 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9108
    - --isolation
    - process
    ports:
    - 9108:9108
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-15:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-15
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-15:9108
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '7.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '7'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '14'
      PROFILE_NAME: High-End Edge CPU
    volumes:
    - logs:/app/logs:rw
  supernode-16:
    image: flwr/supernode:1.15.2
    container_name: supernode-16
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=15 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9109
    - --isolation
    - process
    ports:
    - 9109:9109
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-16:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-16
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-16:9109
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '1.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '1'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '15'
      PROFILE_NAME: Low-End IoT
    volumes:
    - logs:/app/logs:rw
  supernode-17:
    image: flwr/supernode:1.15.2
    container_name: supernode-17
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=16 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9110
    - --isolation
    - process
    ports:
    - 9110:9110
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-17:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-17
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-17:9110
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '4.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '4'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '16'
      PROFILE_NAME: Mid-Range Edge
    volumes:
    - logs:/app/logs:rw
  supernode-18:
    image: flwr/supernode:1.15.2
    container_name: supernode-18
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=17 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9111
    - --isolation
    - process
    ports:
    - 9111:9111
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-18:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-18
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-18:9111
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '5.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '5'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '17'
      PROFILE_NAME: High-End Edge CPU
    volumes:
    - logs:/app/logs:rw
  supernode-19:
    image: flwr/supernode:1.15.2
    container_name: supernode-19
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=18 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9112
    - --isolation
    - process
    ports:
    - 9112:9112
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-19:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-19
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-19:9112
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '2.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '2'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '18'
      PROFILE_NAME: Low-End IoT
    volumes:
    - logs:/app/logs:rw
  supernode-20:
    image: flwr/supernode:1.15.2
    container_name: supernode-20
    command:
    - --insecure
    - --superlink
    - superlink:9092
    - --node-config
    - partition-id=19 num-partitions=20
    - --clientappio-api-address
    - 0.0.0.0:9113
    - --isolation
    - process
    ports:
    - 9113:9113
    networks:
    - flwr-network
    restart: unless-stopped
    volumes:
    - logs:/app/logs:rw
  clientapp-20:
    build:
      context: .
      dockerfile: clientapp.Dockerfile
    image: flwr_clientapp:0.0.1
    container_name: clientapp-20
    command:
    - --insecure
    - --clientappio-api-address
    - supernode-20:9113
    networks:
    - flwr-network
    restart: unless-stopped
    cpus: '2.0'
    shm_size: 1.5gb
    environment:
      ALLOCATED_CORES: '2'
      NUM_CLIENTS: '20'
      LOG_DIR: /app/logs
      PARTITION_ID: '19'
      PROFILE_NAME: Mid-Range Edge
    volumes:
    - logs:/app/logs:rw
networks:
  flwr-network:
    driver: bridge
volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: logs
